platform :android do
  lane :deploy do
    gradle(
      task: "bundle",
      build_type: "Release",
      properties: {
        "android.injected.signing.store.file" => ENV["KEYSTORE_PATH"],
        "android.injected.signing.store.password" => ENV["KEY_STORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["KEY_PASSWORD"],
      }
    )
    upload_to_play_store(
      track: "internal",
      aab: "build/app/outputs/bundle/release/app-release.aab",
      package_name: "ng.edu.unn.lionfm",
      json_key: ENV["PLAY_STORE_JSON_KEY"],
    )
  end

  lane :build_apk do
    gradle(task: "assemble", build_type: "Release")
  end
end
